// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Calendar: typeof import('./src/components/calendar/index.vue')['default']
    CalendarAddModal: typeof import('./src/components/calendar/components/calendar-add-modal.vue')['default']
    CalendarEditModal: typeof import('./src/components/calendar/components/calendar-edit-modal.vue')['default']
    Dialog: typeof import('./src/components/global-component/dialog/index.vue')['default']
    DialogcomView: typeof import('./src/components/dialogcom-view.vue')['default']
    FloatBtn: typeof import('./src/components/float-btn.vue')['default']
    GlobalComponent: typeof import('./src/components/global-component/index.vue')['default']
    Icon: typeof import('./src/components/icon/index.vue')['default']
    LoadingBar: typeof import('./src/components/global-component/loading-bar/index.vue')['default']
    Message: typeof import('./src/components/global-component/message/index.vue')['default']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NCalendar: typeof import('naive-ui')['NCalendar']
    NCard: typeof import('naive-ui')['NCard']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NForm: typeof import('naive-ui')['NForm']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NH1: typeof import('naive-ui')['NH1']
    NH3: typeof import('naive-ui')['NH3']
    NInput: typeof import('naive-ui')['NInput']
    NList: typeof import('naive-ui')['NList']
    NModal: typeof import('naive-ui')['NModal']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTable: typeof import('naive-ui')['NTable']
    NText: typeof import('naive-ui')['NText']
    NThing: typeof import('naive-ui')['NThing']
  }
}

export { }
